Repository Ensembl/ensembl-variation, pull requests merged in 2023-09, with the labels that each got.

#980 Add EVA nextflow pipeline
  nextflow/EVAImport/main.nf
  nextflow/EVAImport/nextflow.config
Labels: e111, nextflow

#1035 Fix MaveDB plugin data creation
  nextflow/MaveDB/bin/map_scores_to_variants.py
  nextflow/MaveDB/nf_modules/fetch.nf
Labels: e111

#1026 Detect input format using VEP code
  modules/Bio/EnsEMBL/Variation/Utils/VEP.pm
Labels: e111

#1023 VEP handling Y PAR variants
  modules/Bio/EnsEMBL/Variation/DBSQL/VariationFeatureAdaptor.pm
Labels: e111

#1011 SIFT/PPH2 eHive pipeline: ignore expected errors
  modules/Bio/EnsEMBL/Variation/Pipeline/ProteinFunction/RunPolyPhen.pm
  modules/Bio/EnsEMBL/Variation/Pipeline/ProteinFunction/RunSift.pm
Labels: e111

#1021 Fix ref codon and ref peptide used for HGVSp
  modules/Bio/EnsEMBL/Variation/TranscriptVariationAllele.pm
  modules/t/vep.t
Labels: e112

#1040 Report consequences for each breakend
  modules/Bio/EnsEMBL/Variation/StructuralVariationFeature.pm
  modules/Bio/EnsEMBL/Variation/StructuralVariationOverlap.pm
  modules/Bio/EnsEMBL/Variation/StructuralVariationOverlapAllele.pm
  modules/Bio/EnsEMBL/Variation/Utils/VariationEffect.pm
  modules/t/structuralVariationFeature.t
  modules/t/structuralVariationOverlap.t
Labels: e112
